name: First Workflow
on: [push]


jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World!"
            - name: Multiline commands
              run: |
                node -v
                npm -v
            - name: More commands
              run: |
                echo "ls -lar"
                ls -lar
                tree
                echo "pwd|"
                pwd
                echo "USER - $USER"
                echo "HOME - $HOME"
