name: Working Dirs and Shells
on: push
defaults:
    run:
        shell: bash
        #working-directory: /home/runner
jobs:
    display-wd-info:
      runs-on: ubuntu-latest
      steps:
        - name: Display working directory and files
          run: |
            pwd
            ls -a
            echo "GITHUB_SHA $GITHUB_SHA"
            echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
            echo "GITHUB_WORKSPACE $GITHUB_WORKSPACE"
        - name: Change Working directory
          working-directory: /home/runner
          run: pwd
          
    display-wd-info-windows:
      runs-on: windows-latest
      steps:
        - name: Display working directory and files
          run: |
            pwd
            ls -a
            echo "GITHUB_SHA $GITHUB_SHA"
            echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
            echo "GITHUB_WORKSPACE $GITHUB_WORKSPACE"
        - name: Python Shell
          shell: python
          run: |
            import platform    
            print(platform.processor())